[2025-10-27T17:15:27.478-0400] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: onboarding_data_pipeline.check_environment manual__2025-10-27T21:15:23.789244+00:00 [queued]>
[2025-10-27T17:15:27.480-0400] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: onboarding_data_pipeline.check_environment manual__2025-10-27T21:15:23.789244+00:00 [queued]>
[2025-10-27T17:15:27.480-0400] {taskinstance.py:1359} INFO - Starting attempt 1 of 3
[2025-10-27T17:15:27.483-0400] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): check_environment> on 2025-10-27 21:15:23.789244+00:00
[2025-10-27T17:15:27.487-0400] {standard_task_runner.py:57} INFO - Started process 62616 to run task
[2025-10-27T17:15:27.492-0400] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'onboarding_data_pipeline', 'check_environment', 'manual__2025-10-27T21:15:23.789244+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/main_pipeline_dag.py', '--cfg-path', '/var/folders/bq/zp7dztbn5yxb9ljzbt_99_dr0000gn/T/tmpn0gxpuau']
[2025-10-27T17:15:27.494-0400] {standard_task_runner.py:85} INFO - Job 5: Subtask check_environment
[2025-10-27T17:15:27.513-0400] {task_command.py:415} INFO - Running <TaskInstance: onboarding_data_pipeline.check_environment manual__2025-10-27T21:15:23.789244+00:00 [running]> on host mithuns-macbook-pro.local
[2025-10-27T17:15:27.528-0400] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='team13@example.com' AIRFLOW_CTX_DAG_OWNER='Team13' AIRFLOW_CTX_DAG_ID='onboarding_data_pipeline' AIRFLOW_CTX_TASK_ID='check_environment' AIRFLOW_CTX_EXECUTION_DATE='2025-10-27T21:15:23.789244+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-27T21:15:23.789244+00:00'
[2025-10-27T17:15:27.529-0400] {logging_mixin.py:151} INFO - Checking environment setup...
[2025-10-27T17:15:27.529-0400] {logging_mixin.py:151} INFO - ✓ Directory exists: /Users/mithundineshkumar/Documents/Development/MLOps/Project/MLOPS-Test1/data-pipeline/airflow/dags/data/raw
[2025-10-27T17:15:27.529-0400] {logging_mixin.py:151} INFO - ✓ Directory exists: /Users/mithundineshkumar/Documents/Development/MLOps/Project/MLOPS-Test1/data-pipeline/airflow/dags/data/processed/cleaned
[2025-10-27T17:15:27.529-0400] {logging_mixin.py:151} INFO - ✓ Directory exists: /Users/mithundineshkumar/Documents/Development/MLOps/Project/MLOPS-Test1/data-pipeline/airflow/dags/data/processed/chunked
[2025-10-27T17:15:27.530-0400] {logging_mixin.py:151} INFO - ✓ Directory exists: /Users/mithundineshkumar/Documents/Development/MLOps/Project/MLOPS-Test1/data-pipeline/airflow/dags/data/curated
[2025-10-27T17:15:27.530-0400] {logging_mixin.py:151} INFO - ✓ Directory exists: /Users/mithundineshkumar/Documents/Development/MLOps/Project/MLOPS-Test1/data-pipeline/airflow/dags/logs/pipeline
[2025-10-27T17:15:27.530-0400] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/opt/anaconda3/envs/oaenv/lib/python3.9/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/Users/mithundineshkumar/Documents/Development/MLOps/Project/MLOPS-Test1/data-pipeline/airflow/dags/main_pipeline_dag.py", line 120, in check_environment
    raise FileNotFoundError(f"Config file not found: {config_path}")
FileNotFoundError: Config file not found: /Users/mithundineshkumar/Documents/Development/MLOps/Project/MLOPS-Test1/data-pipeline/airflow/dags/configs/pipeline_config.yaml
[2025-10-27T17:15:27.533-0400] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=onboarding_data_pipeline, task_id=check_environment, execution_date=20251027T211523, start_date=20251027T211527, end_date=20251027T211527
[2025-10-27T17:15:27.536-0400] {standard_task_runner.py:104} ERROR - Failed to execute job 5 for task check_environment (Config file not found: /Users/mithundineshkumar/Documents/Development/MLOps/Project/MLOPS-Test1/data-pipeline/airflow/dags/configs/pipeline_config.yaml; 62616)
[2025-10-27T17:15:27.545-0400] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-10-27T17:15:27.553-0400] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
