[2025-10-28T13:58:28.010-0400] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-10-28T13:58:28.015-0400] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: onboarding_data_pipeline.check_environment manual__2025-10-28T17:53:21.185423+00:00 [queued]>
[2025-10-28T13:58:28.017-0400] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: onboarding_data_pipeline.check_environment manual__2025-10-28T17:53:21.185423+00:00 [queued]>
[2025-10-28T13:58:28.017-0400] {taskinstance.py:2865} INFO - Starting attempt 2 of 3
[2025-10-28T13:58:28.021-0400] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): check_environment> on 2025-10-28 17:53:21.185423+00:00
[2025-10-28T13:58:28.026-0400] {standard_task_runner.py:72} INFO - Started process 82918 to run task
[2025-10-28T13:58:28.031-0400] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'onboarding_data_pipeline', 'check_environment', 'manual__2025-10-28T17:53:21.185423+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/main_pipeline_dag.py', '--cfg-path', '/var/folders/bq/zp7dztbn5yxb9ljzbt_99_dr0000gn/T/tmplpxd03dt']
[2025-10-28T13:58:28.032-0400] {standard_task_runner.py:105} INFO - Job 18: Subtask check_environment
[2025-10-28T13:58:28.051-0400] {task_command.py:467} INFO - Running <TaskInstance: onboarding_data_pipeline.check_environment manual__2025-10-28T17:53:21.185423+00:00 [running]> on host mithuns-macbook-pro.local
[2025-10-28T13:58:28.074-0400] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='team13@example.com' AIRFLOW_CTX_DAG_OWNER='Team13' AIRFLOW_CTX_DAG_ID='onboarding_data_pipeline' AIRFLOW_CTX_TASK_ID='check_environment' AIRFLOW_CTX_EXECUTION_DATE='2025-10-28T17:53:21.185423+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-28T17:53:21.185423+00:00'
[2025-10-28T13:58:28.074-0400] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-10-28T13:58:28.075-0400] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-10-28T13:58:28.075-0400] {logging_mixin.py:190} INFO - Current task name:check_environment state:running start_date:2025-10-28 17:58:28.015940+00:00
[2025-10-28T13:58:28.075-0400] {logging_mixin.py:190} INFO - Dag name:onboarding_data_pipeline and current dag run status:running
[2025-10-28T13:58:28.076-0400] {taskinstance.py:731} INFO - ::endgroup::
[2025-10-28T13:58:28.076-0400] {logging_mixin.py:190} INFO - Checking environment setup...
[2025-10-28T13:58:28.077-0400] {logging_mixin.py:190} INFO - ✓ Directory exists: /Users/mithundineshkumar/Documents/Development/MLOps/Project/MLOPS-Test1/data-pipeline/data/raw
[2025-10-28T13:58:28.077-0400] {logging_mixin.py:190} INFO - ✓ Directory exists: /Users/mithundineshkumar/Documents/Development/MLOps/Project/MLOPS-Test1/data-pipeline/data/processed/cleaned
[2025-10-28T13:58:28.078-0400] {logging_mixin.py:190} INFO - ✓ Directory exists: /Users/mithundineshkumar/Documents/Development/MLOps/Project/MLOPS-Test1/data-pipeline/data/processed/chunked
[2025-10-28T13:58:28.078-0400] {logging_mixin.py:190} INFO - ✓ Directory exists: /Users/mithundineshkumar/Documents/Development/MLOps/Project/MLOPS-Test1/data-pipeline/data/curated
[2025-10-28T13:58:28.078-0400] {logging_mixin.py:190} INFO - ✓ Directory exists: /Users/mithundineshkumar/Documents/Development/MLOps/Project/MLOPS-Test1/data-pipeline/logs/pipeline
[2025-10-28T13:58:28.079-0400] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 762, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mithundineshkumar/Documents/Development/MLOps/Project/MLOPS-Test1/data-pipeline/airflow/dags/main_pipeline_dag.py", line 123, in check_environment
    raise FileNotFoundError(f"Config file not found: {config_path}")
FileNotFoundError: Config file not found: /Users/mithundineshkumar/Documents/Development/MLOps/Project/MLOPS-Test1/data-pipeline/configs/pipeline_config.yaml
[2025-10-28T13:58:28.084-0400] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-10-28T13:58:28.085-0400] {logging_mixin.py:190} INFO - Task start:2025-10-28 17:58:28.015940+00:00 end:2025-10-28 17:58:28.084205+00:00 duration:0.068265
[2025-10-28T13:58:28.085-0400] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): check_environment> dag:<DAG: onboarding_data_pipeline> dagrun:<DagRun onboarding_data_pipeline @ 2025-10-28 17:53:21.185423+00:00: manual__2025-10-28T17:53:21.185423+00:00, state:running, queued_at: 2025-10-28 17:53:21.221633+00:00. externally triggered: True>
[2025-10-28T13:58:28.085-0400] {logging_mixin.py:190} INFO - Failure caused by Config file not found: /Users/mithundineshkumar/Documents/Development/MLOps/Project/MLOPS-Test1/data-pipeline/configs/pipeline_config.yaml
[2025-10-28T13:58:28.086-0400] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=onboarding_data_pipeline, task_id=check_environment, run_id=manual__2025-10-28T17:53:21.185423+00:00, execution_date=20251028T175321, start_date=20251028T175828, end_date=20251028T175828
[2025-10-28T13:58:28.091-0400] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-10-28T13:58:28.091-0400] {standard_task_runner.py:124} ERROR - Failed to execute job 18 for task check_environment (Config file not found: /Users/mithundineshkumar/Documents/Development/MLOps/Project/MLOPS-Test1/data-pipeline/configs/pipeline_config.yaml; 82918)
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 762, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mithundineshkumar/Documents/Development/MLOps/Project/MLOPS-Test1/data-pipeline/airflow/dags/main_pipeline_dag.py", line 123, in check_environment
    raise FileNotFoundError(f"Config file not found: {config_path}")
FileNotFoundError: Config file not found: /Users/mithundineshkumar/Documents/Development/MLOps/Project/MLOPS-Test1/data-pipeline/configs/pipeline_config.yaml
[2025-10-28T13:58:28.127-0400] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-10-28T13:58:28.135-0400] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-28T13:58:28.136-0400] {local_task_job_runner.py:245} INFO - ::endgroup::
