[2025-10-28T16:12:48.422-0400] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-10-28T16:12:48.425-0400] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: onboarding_data_pipeline.preprocessing_tasks.clean_text manual__2025-10-28T20:07:35.453487+00:00 [queued]>
[2025-10-28T16:12:48.427-0400] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: onboarding_data_pipeline.preprocessing_tasks.clean_text manual__2025-10-28T20:07:35.453487+00:00 [queued]>
[2025-10-28T16:12:48.427-0400] {taskinstance.py:2865} INFO - Starting attempt 2 of 3
[2025-10-28T16:12:48.430-0400] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): preprocessing_tasks.clean_text> on 2025-10-28 20:07:35.453487+00:00
[2025-10-28T16:12:48.433-0400] {standard_task_runner.py:72} INFO - Started process 27883 to run task
[2025-10-28T16:12:48.441-0400] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'onboarding_data_pipeline', 'preprocessing_tasks.clean_text', 'manual__2025-10-28T20:07:35.453487+00:00', '--job-id', '99', '--raw', '--subdir', 'DAGS_FOLDER/main_pipeline_dag.py', '--cfg-path', '/var/folders/bq/zp7dztbn5yxb9ljzbt_99_dr0000gn/T/tmpna2eck6s']
[2025-10-28T16:12:48.444-0400] {standard_task_runner.py:105} INFO - Job 99: Subtask preprocessing_tasks.clean_text
[2025-10-28T16:12:48.461-0400] {task_command.py:467} INFO - Running <TaskInstance: onboarding_data_pipeline.preprocessing_tasks.clean_text manual__2025-10-28T20:07:35.453487+00:00 [running]> on host mithuns-macbook-pro.local
[2025-10-28T16:12:48.485-0400] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='mithun.feb2024@gmail.com' AIRFLOW_CTX_DAG_OWNER='Team13' AIRFLOW_CTX_DAG_ID='onboarding_data_pipeline' AIRFLOW_CTX_TASK_ID='preprocessing_tasks.clean_text' AIRFLOW_CTX_EXECUTION_DATE='2025-10-28T20:07:35.453487+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-28T20:07:35.453487+00:00'
[2025-10-28T16:12:48.486-0400] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-10-28T16:12:48.486-0400] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-10-28T16:12:48.486-0400] {logging_mixin.py:190} INFO - Current task name:preprocessing_tasks.clean_text state:running start_date:2025-10-28 20:12:48.425935+00:00
[2025-10-28T16:12:48.486-0400] {logging_mixin.py:190} INFO - Dag name:onboarding_data_pipeline and current dag run status:running
[2025-10-28T16:12:48.487-0400] {taskinstance.py:731} INFO - ::endgroup::
[2025-10-28T16:12:48.487-0400] {logging_mixin.py:190} INFO - Simulating text cleaning...
[2025-10-28T16:12:48.489-0400] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 762, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mithundineshkumar/Documents/Development/MLOps/Project/MLOPS-Test1/data-pipeline/airflow/dags/main_pipeline_dag.py", line 28, in clean_all_text
    raise Exception("Test failure: This is a simulated task failure to test Airflow email alerts.")
Exception: Test failure: This is a simulated task failure to test Airflow email alerts.
[2025-10-28T16:12:48.492-0400] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-10-28T16:12:48.492-0400] {logging_mixin.py:190} INFO - Task start:2025-10-28 20:12:48.425935+00:00 end:2025-10-28 20:12:48.492507+00:00 duration:0.066572
[2025-10-28T16:12:48.493-0400] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): preprocessing_tasks.clean_text> dag:<DAG: onboarding_data_pipeline> dagrun:<DagRun onboarding_data_pipeline @ 2025-10-28 20:07:35.453487+00:00: manual__2025-10-28T20:07:35.453487+00:00, state:running, queued_at: 2025-10-28 20:07:35.465746+00:00. externally triggered: True>
[2025-10-28T16:12:48.493-0400] {logging_mixin.py:190} INFO - Failure caused by Test failure: This is a simulated task failure to test Airflow email alerts.
[2025-10-28T16:12:48.493-0400] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=onboarding_data_pipeline, task_id=preprocessing_tasks.clean_text, run_id=manual__2025-10-28T20:07:35.453487+00:00, execution_date=20251028T200735, start_date=20251028T201248, end_date=20251028T201248
[2025-10-28T16:12:48.498-0400] {base.py:84} INFO - Retrieving connection 'smtp_default'
[2025-10-28T16:12:48.499-0400] {email.py:272} INFO - Email alerting: attempt 1
[2025-10-28T16:12:49.075-0400] {email.py:283} INFO - Sent an alert email to ['mithun.feb2024@gmail.com']
[2025-10-28T16:12:51.517-0400] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-10-28T16:12:51.517-0400] {standard_task_runner.py:124} ERROR - Failed to execute job 99 for task preprocessing_tasks.clean_text (Test failure: This is a simulated task failure to test Airflow email alerts.; 27883)
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 762, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mithundineshkumar/Documents/Development/MLOps/Project/MLOPS-Test1/data-pipeline/airflow/dags/main_pipeline_dag.py", line 28, in clean_all_text
    raise Exception("Test failure: This is a simulated task failure to test Airflow email alerts.")
Exception: Test failure: This is a simulated task failure to test Airflow email alerts.
[2025-10-28T16:12:51.529-0400] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-10-28T16:12:51.537-0400] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-28T16:12:51.538-0400] {local_task_job_runner.py:245} INFO - ::endgroup::
